BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "brand" (
	"id"	INTEGER NOT NULL UNIQUE,
	"name"	TEXT NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "specification" (
	"id"	INTEGER NOT NULL UNIQUE,
	"item_id"	INTEGER NOT NULL,
	"key"	TEXT,
	"value"	TEXT,
	PRIMARY KEY("id" AUTOINCREMENT),
	FOREIGN KEY("item_id") REFERENCES "item"("id")
);
CREATE TABLE IF NOT EXISTS "item" (
	"id"	INTEGER NOT NULL UNIQUE,
	"brand_id"	INTEGER NOT NULL,
	"model"	TEXT NOT NULL,
	"slug"	INTEGER NOT NULL UNIQUE,
	"description"	TEXT,
	"thumbnail"	TEXT NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT),
	FOREIGN KEY("brand_id") REFERENCES "brand"("id")
);
COMMIT;
